[package]
name = "llm_chatbot"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
candid = "0.10"
ic-cdk = "0.13"
ic-llm = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0" # This line fixes the errors
