[package]
name = "dao_agreement"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
candid = "0.10.10"
ic-cdk = "0.16.0"
ic-cdk-macros = "0.13"
ic-stable-structures = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
